# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
#  main 브랜치에 push가 될 때
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  test:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
#      - run: npm ci
#      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.test}}
